version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: mcp-server
    ports:
      - "8001:8001"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY1}
      - OPENROUTER_MODEL=x-ai/grok-4-fast
      - MCP_API_KEY=${MCP_API_KEY:-mcp-secret-key}
    volumes:
      - ./swarms:/app/swarms
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  swarm-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swarm-api
    ports:
      - "8000:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY1}
      - OPENROUTER_MODEL=x-ai/grok-4-fast
      - MCP_URL=http://mcp-server:8001
      - MCP_API_KEY=${MCP_API_KEY:-mcp-secret-key}
    volumes:
      - ./swarms:/app/swarms
    depends_on:
      - mcp-server
    restart: unless-stopped

volumes:
  swarms:
