name: Xen ARM64 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gcc-aarch64-linux-gnu \
          pkg-config \
          libncurses5-dev \
          libssl-dev \
          python3 \
          python3-dev \
          python3-setuptools \
          python3-pip \
          uuid-dev \
          qemu-system-arm \
          bison \
          flex
        pip3 install --user cryptography

    - name: Compile test suite
      run: |
        mkdir -p test-output
        # Compile C trap test
        aarch64-linux-gnu-gcc -o test-output/qemu-trap-test \
          tests/qemu-trap-test.c -static -O2
        # Compile ASM test
        aarch64-linux-gnu-as tests/trap-trigger-arm64.S \
          -o test-output/trap-trigger.o
        aarch64-linux-gnu-ld -o test-output/trap-trigger \
          test-output/trap-trigger.o

    - name: Run tests in QEMU
      run: |
        mkdir -p test-logs
        # Run C test
        timeout 30s qemu-aarch64 test-output/qemu-trap-test 2>&1 | \
          tee test-logs/trap-test.log || true
        
    - name: Parse test results
      run: |
        LOG_FILE="test-logs/trap-test.log"
        if [ ! -f "$LOG_FILE" ]; then
          echo "❌ No log file generated"
          exit 1
        fi
        
        # Count passes
        PASSES=$(grep -c "PASS:" "$LOG_FILE" || true)
        FAILS=$(grep -c "FAIL:" "$LOG_FILE" || true)
        
        echo "✅ Tests passed: $PASSES"
        echo "❌ Tests failed: $FAILS"
        
        if [ "$FAILS" -gt 0 ]; then
          echo "Test failures detected!"
          exit 1
        fi
        
        if [ "$PASSES" -eq 0 ]; then
          echo "No tests passed!"
          exit 1
        fi
        
        echo "🎉 All tests passed!"

    - name: Upload test logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: xen-arm64-test-logs
        path: test-logs/

    - name: Upload test binaries
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: xen-arm64-tests
        path: test-output/
